language: php

php:
    - "5.5"
    - "5.2"

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1

services:
    - elasticsearch

before_script:
    - composer install --dev
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - sleep 5

script:
    - mkdir -p build/logs
    - phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls
    - ./vendor/bin/test-reporter
