language: php

php:
    - "5.5"
    - "5.2"

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1

services:
    - elasticsearch

before_script:
    - mkdir -p build/logs
    - if [ $(phpenv version-name) -gt 5.2 ]; then composer install --dev; fi;
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - sleep 5

script:
    - if [ $(phpenv version-name) -gt 5.2 ]; then phpunit --coverage-clover build/logs/clover.xml; fi;
    - if [ $(phpenv version-name) -lte 5.2 ]; then phpunit; fi;

after_script:
    - if [ $(phpenv version-name) -gt 5.2 ]; then php vendor/bin/coveralls; fi;
    - if [ $(phpenv version-name) -gt 5.2 ]; then ./vendor/bin/test-reporter; fi;
