language: php

php:
    - "5.2"

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1

script:
    - if [ "$(phpenv version-name)" == "5.2" ]; then echo "hooray"; fi;
